name: orbot-venv
dependencies:
  - pip
  - pip:
      - aiohttp
      - asyncpg
      - discord.py
      - ruamel.yaml
      - python-dotenv
      - stringcase
      - tweepy[async]
      - python-dateutil
      - typing-extensions
      - black
      - isort
      - emoji
